### ISSUE TITLE
Feature request: Use a button for guest login instead

### ISSUE THREAD

**Issue by jelle619** [TitanEmbeds/Titan#118]
Request by Nihbru#1391

"is it possible to add a button for the guest login? something like this maybe.."
"From my POV it's easy to log in, its just some of my users aren't techy and because it's a radio station, they're not prepared to do much reading since they're not overly engaged or motivated, if possible, a button like that would be really great :smiley:"

https://cdn.discordapp.com/attachments/300367171442442241/475342898112626698/guest-login-button.jpg

**Comment by EndenDragon** [comment]
Implemented in https://github.com/TitanEmbeds/Titan/commit/0a88e950d6348414227860b3598a4d59263d7db6

The button is initially hidden and is not normally visible to maintain backwards compatibility and sustain small embed widths.

Use custom css like this to display the button nicely:
```css
#guestlogin_btn {
	display: inline-block;
	padding-left: 10px;
	padding-right: 10px;
	margin-top: 7px;
}

#guest_login_instr {
	display: none;
}

#custom_username_field_label {
	display: none;
}

#guestlogin_box {
	display: flex;
}

```
