### ISSUE TITLE
Constant colors in embed.css

### ISSUE THREAD

**Issue by Maxilver** [TitanEmbeds/Titan#144]
Hi! 

Thanks for the widget, it's really good tool :)
I've noticed that some of styles in `embed.css` is using only constant color w/o var() from the theme.
E.g. 
```css
#modal_guildinfobox {
  background-color: #455a64;
  padding-top: 10px;
  padding-bottom: 10px;
}
```

Always will display Fiord color without regardless of the theme.
![image](https://user-images.githubusercontent.com/12146391/86294052-195a8b00-bbf4-11ea-9c3d-7bf3097f3ed4.png)

I guess it could be easily fixed by custom CSS, but would be awesome to cover const styles with relevant variables.

**Comment by Maxilver** [comment]
For `#modal_guidinfobox` I guess it should be `--main`

```css
#modal_guildinfobox {
  background-color: #455a64;
  background-color: var(--main);
  padding-top: 10px;
  padding-bottom: 10px;
}
```
